"""
Test script to verify CSV question-answering functionality.
This script sends a CSV file to the backend and asks questions about it.
"""

import asyncio
import json
import websockets
from pathlib import Path


async def test_csv_qa():
    """Test CSV question answering via WebSocket."""

    # Read the sample CSV file
    csv_path = Path(__file__).parent / "fixtures" / "sample_data.csv"
    with open(csv_path, "r") as f:
        csv_data = f.read()

    print("=" * 60)
    print("CSV Content:")
    print("=" * 60)
    print(csv_data)
    print("=" * 60)

    # Test questions about the CSV
    query = "Do the proper analysis of the data provided."
    user_id = "test_user"
    session_id = None  # Will be generated by the server

    print(f"\n{'='*60}")
    print(f"Question: {query}")
    print("=" * 60)

    try:
        async with websockets.connect("ws://localhost:8000/chat/ws") as ws:
            # Send the request
            request = {
                "query": query,
                "user_id": user_id,
                "session_id": session_id,
                "include_reasoning": False,  # Match frontend failure condition
                "csv_data": csv_data,
            }

            await ws.send(json.dumps(request))
            print("\n[Sent request, waiting for response...]\n")

            # Receive streaming response
            final_answer = ""

            while True:
                try:
                    response = await asyncio.wait_for(
                        ws.recv(), timeout=70
                    )  # >60s backend timeout
                    event = json.loads(response)

                    if event["type"] == "info":
                        session_id = event.get("session_id", session_id)
                        print(f"[INFO] Session ID: {session_id}")

                    elif event["type"] == "token":
                        # Print tokens as they come in
                        print(event["content"], end="", flush=True)

                    elif event["type"] == "observation":
                        print(f"\n[OBSERVATION]\n{event['content']}")

                    elif event["type"] == "error":
                        print(f"\n[ERROR] {event['content']}")

                    elif event["type"] == "step_separator":
                        print("\n--- Step Complete ---\n")

                    elif event["type"] == "final":
                        final_answer = event["content"]
                        print(f"\n\n{'='*60}")
                        print(f"FINAL ANSWER: {final_answer}")
                        print("=" * 60)
                        break

                except asyncio.TimeoutError:
                    print("\n[TIMEOUT] No response received in 70 seconds")
                    break

    except Exception as e:
        print(f"\n[CONNECTION ERROR] {e}")


async def test_csv_http():
    """Test CSV question answering via HTTP endpoint."""
    import aiohttp

    # Read the sample CSV file
    csv_path = Path(__file__).parent / "fixtures" / "sample_data.csv"
    with open(csv_path, "r") as f:
        csv_data = f.read()

    print("=" * 60)
    print("Testing HTTP Endpoint")
    print("=" * 60)

    question = "What is the average salary per department?"

    request = {
        "query": question,
        "user_id": "test_user_http",
        "include_reasoning": True,
        "csv_data": csv_data,
    }

    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(
                "http://localhost:8000/chat/",
                json=request,
                timeout=aiohttp.ClientTimeout(total=120),
            ) as response:
                result = await response.json()
                print(f"\nQuestion: {question}")
                print(f"\nResponse: {result.get('response', 'No response')}")
                print(f"Session ID: {result.get('session_id', 'N/A')}")

    except Exception as e:
        print(f"Error: {e}")


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == "--http":
        asyncio.run(test_csv_http())
    else:
        asyncio.run(test_csv_qa())
